{
  "name": "PR2",
  "version": "0.0.1",
  "description": "PR2 Core System",
  "main": "app.js",
  "dependencies": {
    "async": "1.5.2",
    "bluebird": "3.3.4",
    "body-parser": "~1.15.0",
    "bower": "^1.7.9",
    "commander": "2.9.0",
    "connect": "~3.4.1",
    "connect-assets": "^5.3.2",
    "connect-ensure-login": "^0.1.1",
    "connect-redis": "3.0.2",
    "connect-roles": "3.1.2",
    "cookie-parser": "~1.4.1",
    "ejs": "2.4.1",
    "express": "~4.13.4",
    "express-session": "^1.13.0",
    "glob": "7.0.3",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-clean-css": "^2.0.6",
    "gulp-mincer": "0.0.2",
    "handlebars": "^4.0.5",
    "htmlparser2": "3.9.1",
    "i18n": "^0.8.2",
    "jwt-simple": "^0.5.0",
    "kue": "0.10.5",
    "lin-reqrep": "0.2.2",
    "machina": "2.0.0",
    "method-override": "^2.3.5",
    "mincer": "^1.5.0",
    "moment": "2.13.0",
    "mqtt": "^2.0.1",
    "multer": "0.1.8",
    "node-rsa": "^0.4.2",
    "node-uuid": "1.4.7",
    "passport": "0.3.2",
    "passport-oauth2-password-grant": "0.0.3",
    "passport-saml": "^0.15.0",
    "passport-unique-token": "0.1.4",
    "passports": "^0.2.1",
    "pg": "4.5.5",
    "protobufjs": "^5.0.1",
    "redis": "^2.6.3",
    "rimraf": "^2.5.4",
    "sanitize-html": "^1.13.0",
    "sequelize": "git@github.com:molotowtales/sequelize.git#v3.19.3-fork",
    "sequelize-cli": "2.3.1",
    "sequelize-hierarchy": "^1.0.0",
    "session-retry": "0.0.1",
    "slug": "^0.9.1",
    "strong-params": "^0.7.0",
    "supertest-as-promised": "^3.1.0",
    "underscore": "~1.8.3",
    "useragent": "^2.1.9",
    "winston": "2.2.0"
  },
  "engines": {
    "node": "6.6.0"
  },
  "devDependencies": {
    "jsdoc": "^3.4.0",
    "mocha": "2.4.5",
    "should": "8.2.2",
    "sinon": "^1.17.3",
    "supertest": "1.1.0",
    "supervisor": "0.9.1"
  },
  "scripts": {
  },
  "repository": "git@github.com:lineducation/pr2-core.git",
  "contributors": [
    {
      "name": "Daniel Sundström",
      "email": "daniel.sundstrom@lineducation.se",
      "url": "www.danielsundstrom.com"
    }
  ]
}
